version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  print_pipeline_id:
    parameters:
      id: 
        type: string
    steps:
      - run: echo << parameters.id >>


jobs:
  print_greetings:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
      - run: echo HELLO
      - run: echo Darkness my old friend
      - run: echo $_env_name

  upload_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "THIS IS A SAMPLE TEXT" > ~/output.txt  
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt  

  download_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt 

  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Configure AWS Access Key ID
          command: aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
      - run:
          name: Configure AWS Secret Access Key
          command: aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - run:
          name: Configure AWS Region
          command: aws configure set default.region ${AWS_DEFAULT_REGION}
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1



workflows:
  my_workflow:
    jobs:
      - print_greetings
      - upload_file
      - download_file:
          requires:
            - upload_file
      - create_infrastructure
      